name: ${project.name}
main: com.setupsafari.welcomemessage.Main
version: ${project.version}
description: on join it will announce the player has joined.
website: https://setupsafari.com/
author: Squidguy
