name: ${project.name}
main: com.setupsafari.welcomemessage.Main
version: ${project.version}
description: This plugin mekes it so theres a meaning to your life
website: https://cyberfla.me/
author: CyberFlame
